version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: "auto"
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "fix(deps)"
      prefix-development: "chore(deps-dev)"
    groups:
      dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "react"
      - dependency-name: "react-dom"

  - package-ecosystem: "npm"
    directory: "/apps/web"
    schedule:
      interval: "weekly"
    versioning-strategy: "auto"
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "fix(deps)"
      prefix-development: "chore(deps-dev)" 